### PR TITLE
Haskell-CI on github for GHC 7.0 - 9.4

### PR DESCRIPTION
**Pull request by andreasabel**
Haskell-CI on github for GHC 7.0 - 9.4

Also fixes:
- #10

Successful run at: https://github.com/andreasabel/haskell-lexer/actions/runs/2717668809

Ok to squash before merging.

ATTN: @yav

### CODE REVIEW

**Comment by yav** [comment]
Thanks!

**Comment by andreasabel** [comment]
@yav: Iavor, can I get this released to hackage?

**Comment by yav** [comment]
OK, should be up as version 1.1.1

**Comment by andreasabel** [comment]
Excellent, thanks for the Christmas present!

**Pull request merged**
