### PR TITLE
Bump CI to latest GHC version, drop GHC <= 7.8 in CI

### PR DESCRIPTION
**Pull request by andreasabel**
GHCs older than 7.10 will not be supported by Haskell CI in the future.

### CODE REVIEW

**Comment by andreasabel** [comment]
@yav : I bumped this to GHC 9.8.1 and the latest major versions of 9.2-9.6.

Can this be merged?

**Comment by andreasabel** [comment]
@yav Friendly reminder.

**Comment by andreasabel** [comment]
@yav:  I added GHC 9.10 alpha to the CI.

**Comment by andreasabel** [comment]
@yav : CI updated to GHC 9.10.1, drop GHC 7

**Comment by yav** [comment]
Sorry, I've completely missed the notifications for these.   Thanks for the PR!

**Comment by andreasabel** [comment]
> Sorry, I've completely missed the notifications for these.

Thanks for the attention.  
Hopefully you fixed your notification settings now.

Btw, can you release?  See my ignored request at https://github.com/yav/haskell-lexer/pull/12#issuecomment-1751961504

**Comment by yav** [comment]
@andreasabel I just uploaded 1.1.2 to hackage

**Pull request merged**
